iOS binding and demo
Picovoice/cheetah pull request #55
Opened 2022-02-03 21:33 UTC by ksyeo1010

2022-02-04 01:38 UTC, kenarsa requested changes

2022-02-04 01:38 UTC, kenarsa commented on README.md
> +The Cheetah iOS binding is available via [Cocoapods](https://cocoapods.org/pods/Cheetah-iOS). To import it into your iOS project, add the following line to your Podfile and run `pod install`:
`Cocoapods` >>> `CocoaPods`

2022-02-04 01:38 UTC, kenarsa commented on README.md
> +  } catch { }
should we set the type to CheetahError?

2022-02-04 01:38 UTC, kenarsa commented on README.md
> +Replace `${ACCESS_KEY}` with yours obtained from Picovoice Console and `${MODEL_FILE}` with the name of the Cheetah model file name.
default or custom trained from Console (something like that and maybe a link to default model)

2022-02-04 01:38 UTC, kenarsa commented on binding/ios/Cheetah.swift
> +/// iOS binding for Cheetah wake word engine. Provides a Swift interface to the Cheetah library.
wake word engine ??? :(((

2022-02-04 01:38 UTC, kenarsa commented on binding/ios/Cheetah.swift
> +        if endpointDuration <= 0 {
I think `0` should be acceptable?

2022-02-04 01:38 UTC, kenarsa commented on binding/ios/Cheetah.swift
> +        if pcm.count == 0 {
we should check that the length is equal to our expected frame length

2022-02-04 01:38 UTC, kenarsa commented on binding/ios/README.md
> +    - Android and iOS
same order as the main README.md

2022-02-04 01:38 UTC, kenarsa commented on binding/ios/README.md
> +The Cheetah iOS binding is available via [Cocoapods](https://cocoapods.org/pods/Cheetah-iOS). To import it into your iOS project, add the following line to your Podfile:
`Cocoapods` >>> `CocoaPods`

2022-02-04 01:38 UTC, kenarsa commented on binding/ios/README.md
> +Replace `${ACCESS_KEY}` with yours obtained from [Picovoice Console]((https://console.picovoice.ai/)) and `${MODEL_FILE}` with the name of the Cheetah model file name. Finally, when done be sure to e
a couple of lines where they can get the default and how to train a custom one

2022-02-04 18:14 UTC, wasauce commented
@ksyeo1010 does cheetah do punctuation and capitalization?

2022-02-07 17:38 UTC, kenarsa requested changes

2022-02-07 17:57 UTC, merged