Initial Android binding + demo
Picovoice/cheetah pull request #57
Opened 2022-02-09 08:16 UTC by ErisMik

2022-02-09 17:55 UTC, ErisMik commented
> I get invalid argument error for simulator/device -> tests all pass except getFrameLength

You get Invalid Argument even just trying to run the demo?

2022-02-09 17:56 UTC, ksyeo1010 commented
> > I get invalid argument error for simulator/device -> tests all pass except getFrameLength
> 
> You get Invalid Argument even just trying to run the demo?

yes

2022-02-10 00:35 UTC, ErisMik commented
> do we need to add libs to lib directory?

Yes ;)

2022-02-10 20:52 UTC, ksyeo1010 approved these changes

2022-02-11 00:07 UTC, kenarsa requested changes

2022-02-11 00:07 UTC, kenarsa commented on binding/android/cheetah/src/main/java/ai/picovoice/cheetah/Cheetah.java
> +     * @throws CheetahException if there is an error while initializing Cheetah.
missing doc for `endpointDuration`

2022-02-11 01:11 UTC, merged