react native binding demo
Picovoice/cheetah pull request #60
Opened 2022-02-19 00:36 UTC by ksyeo1010

- add react native binding and demo

2022-02-22 18:28 UTC, ErisMik approved these changes

2022-02-23 18:49 UTC, kenarsa requested changes

2022-02-23 18:49 UTC, kenarsa commented on README.md
> +Replace `${ACCESS_KEY}` with yours obtained from Picovoice Console and `${MODEL_FILE}` with the default or custom trained model from [console](https://console.picovoice.ai/).
release

2022-02-23 18:49 UTC, kenarsa commented on binding/react-native/README.md
> +- Compact and Computationally-Efficient [[2]](https://github.com/Picovoice/speech-to-text-benchmark#results)
`#rtf`

2022-02-23 18:49 UTC, kenarsa commented on binding/react-native/README.md
> +To start install be sure you have installed yarn and cocoapods. Then add these two native modules to your react-native project.
CocoaPods

2022-02-24 18:57 UTC, merged